/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DefectsRouteImport } from './routes/defects'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkspaceProjectIdRouteImport } from './routes/workspace.$projectId'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsPermissionsRouteImport } from './routes/settings.permissions'
import { Route as SettingsAdminRouteImport } from './routes/settings.admin'
import { Route as RequirementsReqIdRouteImport } from './routes/requirements.$reqId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as IntegrationsPolarionRouteImport } from './routes/integrations.polarion'
import { Route as IntegrationsJiraRouteImport } from './routes/integrations.jira'
import { Route as IntegrationsAzureRouteImport } from './routes/integrations.azure'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsRoute = DefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkspaceProjectIdRoute = WorkspaceProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdminRoute = SettingsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SettingsRoute,
} as any)
const RequirementsReqIdRoute = RequirementsReqIdRouteImport.update({
  id: '/requirements/$reqId',
  path: '/requirements/$reqId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const IntegrationsPolarionRoute = IntegrationsPolarionRouteImport.update({
  id: '/polarion',
  path: '/polarion',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsJiraRoute = IntegrationsJiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsAzureRoute = IntegrationsAzureRouteImport.update({
  id: '/azure',
  path: '/azure',
  getParentRoute: () => IntegrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/defects': typeof DefectsRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/traceability': typeof TraceabilityRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/integrations/azure': typeof IntegrationsAzureRoute
  '/integrations/jira': typeof IntegrationsJiraRoute
  '/integrations/polarion': typeof IntegrationsPolarionRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/requirements/$reqId': typeof RequirementsReqIdRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/defects': typeof DefectsRoute
  '/reports': typeof ReportsRoute
  '/traceability': typeof TraceabilityRoute
  '/integrations/azure': typeof IntegrationsAzureRoute
  '/integrations/jira': typeof IntegrationsJiraRoute
  '/integrations/polarion': typeof IntegrationsPolarionRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/requirements/$reqId': typeof RequirementsReqIdRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/defects': typeof DefectsRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/traceability': typeof TraceabilityRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/integrations/azure': typeof IntegrationsAzureRoute
  '/integrations/jira': typeof IntegrationsJiraRoute
  '/integrations/polarion': typeof IntegrationsPolarionRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/requirements/$reqId': typeof RequirementsReqIdRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/defects'
    | '/integrations'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/workspace'
    | '/integrations/azure'
    | '/integrations/jira'
    | '/integrations/polarion'
    | '/projects/$projectId'
    | '/projects/new'
    | '/requirements/$reqId'
    | '/settings/admin'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
    | '/workspace/$projectId'
    | '/admin/'
    | '/integrations/'
    | '/projects/'
    | '/settings/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/defects'
    | '/reports'
    | '/traceability'
    | '/integrations/azure'
    | '/integrations/jira'
    | '/integrations/polarion'
    | '/projects/$projectId'
    | '/projects/new'
    | '/requirements/$reqId'
    | '/settings/admin'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
    | '/workspace/$projectId'
    | '/admin'
    | '/integrations'
    | '/projects'
    | '/settings'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/defects'
    | '/integrations'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/workspace'
    | '/integrations/azure'
    | '/integrations/jira'
    | '/integrations/polarion'
    | '/projects/$projectId'
    | '/projects/new'
    | '/requirements/$reqId'
    | '/settings/admin'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
    | '/workspace/$projectId'
    | '/admin/'
    | '/integrations/'
    | '/projects/'
    | '/settings/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  DefectsRoute: typeof DefectsRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TraceabilityRoute: typeof TraceabilityRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  RequirementsReqIdRoute: typeof RequirementsReqIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects': {
      id: '/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof DefectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/admin': {
      id: '/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof SettingsAdminRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/requirements/$reqId': {
      id: '/requirements/$reqId'
      path: '/requirements/$reqId'
      fullPath: '/requirements/$reqId'
      preLoaderRoute: typeof RequirementsReqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/integrations/polarion': {
      id: '/integrations/polarion'
      path: '/polarion'
      fullPath: '/integrations/polarion'
      preLoaderRoute: typeof IntegrationsPolarionRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/jira': {
      id: '/integrations/jira'
      path: '/jira'
      fullPath: '/integrations/jira'
      preLoaderRoute: typeof IntegrationsJiraRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/azure': {
      id: '/integrations/azure'
      path: '/azure'
      fullPath: '/integrations/azure'
      preLoaderRoute: typeof IntegrationsAzureRouteImport
      parentRoute: typeof IntegrationsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsAzureRoute: typeof IntegrationsAzureRoute
  IntegrationsJiraRoute: typeof IntegrationsJiraRoute
  IntegrationsPolarionRoute: typeof IntegrationsPolarionRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsAzureRoute: IntegrationsAzureRoute,
  IntegrationsJiraRoute: IntegrationsJiraRoute,
  IntegrationsPolarionRoute: IntegrationsPolarionRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAdminRoute: typeof SettingsAdminRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdminRoute: SettingsAdminRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceProjectIdRoute: typeof WorkspaceProjectIdRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceProjectIdRoute: WorkspaceProjectIdRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  DefectsRoute: DefectsRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TraceabilityRoute: TraceabilityRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  RequirementsReqIdRoute: RequirementsReqIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
